[package]
name = "DesignPattern"
version = "0.1.0"
edition = "2021"

[[example]]
name = "composite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_delegate = "0.2.0"
